apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: cluster
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper
    clusters:
      - name: "shard1-repl1"
        layout:
          shardsCount: 2
          replicasCount: 2
  defaults:
    templates:
      podTemplate: pod-template
      dataVolumeClaimTemplate: default
  templates:
    volumeClaimTemplates:
        - name: default
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 500Mi
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: itcoursevideochat/clickhouse:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: clickhouse-config-volume
                  mountPath: /etc/clickhouse-server/config.d/rabbit
              env:
                - name: RABBITMQ_USER
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-default-user
                      key: username
                - name: RABBITMQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq-default-user
                      key: password
          volumes:
          - name: clickhouse-config-volume
            configMap:
              name: clickhouse-config
              items:
              - key: config.xml
                path: rabbitmq.xml
