apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: cluster
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper
    users:
      videochat/password: "videochat"
      videochat/access_management: 0
    clusters:
      - name: "clcluster"
        layout:
          shardsCount: 2
          replicasCount: 2
  defaults:
    templates:
      podTemplate: pod-template
      dataVolumeClaimTemplate: default
  templates:
    volumeClaimTemplates:
        - name: default
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 500Mi
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: itcoursevideochat/clickhouse:latest
              imagePullPolicy: IfNotPresent
