kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: default 
spec:
  selector:
    app: kafka-manager
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
