apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: itcoursevideochat/clickhouse
      context: clickhouse
    - image: itcoursevideochat/grafana
      context: grafana
    - image: itcoursevideochat/nginx
      context: nginx
    - image: itcoursevideochat/prometheus
      context: prometheus
    - image: itcoursevideochat/rest
      context: rest_server
    - image: itcoursevideochat/sfu
      context: sfu_server
    - image: itcoursevideochat/tarantool
      context: tarantool
    - image: itcoursevideochat/turn
      context: turn
deploy:
  kubectl:
    manifests:
      - monitoring/*.yaml
      - turn/k8s-*.yaml
      - prometheus/k8s-*.yaml
      - grafana/k8s-*.yaml
      - zookeeper/k8s-*.yaml
      - clickhouse/k8s-*.yaml
      - nginx/k8s-*.yaml
      - rabbitmq/k8s-*.yaml
      - rest_server/k8s-*.yaml
      - sfu_server/k8s-*.yaml
      - tarantool/k8s-*.yaml

profiles:
  - name: minikube-profile
    # automatically activate this profile when current context is "minikube"
    activation:
      - kubeContext: minikube

