apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: itcoursevideochat/clickhouse
      context: clickhouse
    - image: itcoursevideochat/grafana
      context: grafana
    - image: itcoursevideochat/nginx
      context: nginx
    - image: itcoursevideochat/prometheus
      context: prometheus
    - image: itcoursevideochat/rabbitmq
      context: rabbitmq
    - image: itcoursevideochat/rest
      context: rest_server
    - image: itcoursevideochat/sfu
      context: sfu_server
    - image: itcoursevideochat/tarantool
      context: tarantool
    - image: itcoursevideochat/turn
      context: turn
deploy:
  kubectl:
    manifests:
      - common/*
      - monitoring/*
      - clickhouse/k8s-*
      - nginx/k8s-*
      - rabbitmq/k8s-*
      - rest_server/k8s-*
      - sfu_server/k8s-*
      - tarantool/k8s-*
      - turn/k8s-*
      - zookeeper/k8s-*
