kind: Service
apiVersion: v1
metadata:
  name: rest
  labels:
    k8s-app: rest
spec:
  ports:
    - name: tcp-3000-3000-mstrq
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    k8s-app: rest
  type: ClusterIP
  sessionAffinity: "ClientIP" 
status:
  loadBalancer: {}

