apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rest
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta2
    kind: Deployment
    name: rest
  targetCPUUtilizationPercentage: 15
