kind: Service
apiVersion: v1
metadata:
  name: nginx-metrics
  labels:
    k8s-app: nginx-metrics
spec:
  selector:
    k8s-app: nginx
  ports:
  - name: stub
    port: 8080
---
apiVersion: v1
kind: Pod 
metadata:
  name: nginx-exporter
  labels:
    k8s-app: nginx-exporter
spec:
  containers:
    - name: nginx-exporter
      image: 'nginx/nginx-prometheus-exporter'
      args: ["-nginx.scrape-uri", "http://nginx-metrics:8080/stub_status"]
      ports:
        - containerPort: 9113
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  enableServiceLinks: true
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-monitoring
  labels:
    k8s-app: nginx-monitoring
spec:
  selector:
    k8s-app: nginx-exporter
  ports:
  - name: prometheus 
    port: 9113
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitoring
  namespace: monitoring 
  labels:
    target: prometheus
spec:
  selector:
    matchLabels:
      k8s-app: nginx-monitoring
  endpoints:
  - port: prometheus
    interval: 3s
    path: /metrics
  namespaceSelector:
    matchNames:
      - default
