kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-monitoring
  labels:
    k8s-app: rabbitmq-monitoring
spec:
  selector:
    k8s-app: rabbitmq
  ports:
  - name: prometheus
    port: 15692
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq-monitoring
  namespace: monitoring 
  labels:
    target: prometheus
spec:
  selector:
    matchLabels:
      k8s-app: rabbitmq-monitoring
  endpoints:
  - port: prometheus
    interval: 3s
    path: /metrics
  namespaceSelector:
    matchNames:
      - default


