kind: Service
apiVersion: v1
metadata:
  name: clickhouse 
  labels:
    k8s-app: clickhouse 
spec:
  ports:
    - name: http 
      protocol: TCP
      port: 8123 
      targetPort: 8123 
    - name: native
      protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    k8s-app: clickhouse 
  type: LoadBalancer 
  sessionAffinity: None


