apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
    name: "demo-02"
spec:
    defaults:
        templates:
            podTemplate: clickhouse-stable
            volumeClaimTemplate: storage-vc-template
    templates:
        podTemplates:
            - name: clickhouse-stable
              spec:
                containers:
                    - name: clickhouse
                      image: yandex/clickhouse-server:19.6.2.11
        volumeClaimTemplates:
            - name: storage-vc-template
              persistentVolumeClaim:
                spec:
                    accessModes:
                        - ReadWriteOnce
                    resources:
                        requests:
                            storage: 2Gi
    configuration:
        zookeeper:
            nodes:
                - host: zookeeper-0.zookeepers.zoo1ns
        clusters:
            - name: "demo"
              layout:
                shardsCount: 2
                replicasCount: 2