apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse 
spec:
  selector:
    matchLabels:
      k8s-app: clickhouse 
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: clickhouse 
    spec:
      containers:
        - name: clickhouse 
          image: 'itcoursevideochat/clickhouse:latest'
          ports:
            - containerPort: 9000 
            - containerPort: 8123 
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: clickhouse-config-volume
              mountPath: /etc/clickhouse-server/config.d
      restartPolicy: Always
      enableServiceLinks: true
      volumes:
      - name: clickhouse-config-volume
        configMap:
          name: clickhouse-config
          items:
          - key: config.xml
            path: rabbitmq.xml
