apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "cluster"
spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper
    clusters:
      - name: "shard1-repl1"
        layout:
          shardsCount: 1
          replicasCount: 2
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: itcoursevideochat/clickhouse:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: clickhouse-config-volume
                  mountPath: /etc/clickhouse-server/config.d
          volumes:
          - name: clickhouse-config-volume
            configMap:
              name: clickhouse-config
              items:
              - key: config.xml
                path: rabbitmq.xml
