kind: Service
apiVersion: v1
metadata:
  name: mongo
  labels:
    k8s-app: mongo
spec:
  ports:
    - name: tcp-27017-27017-qjnlr
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    k8s-app: mongo
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}

