kind: Pod
apiVersion: v1
metadata:
  name: mongo
  labels:
    k8s-app: mongo
spec:
  containers:
    - name: mongo
      image: mongo
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret
      resources: {}
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status: {}
