kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  ports:
    - name: tcp-80-80-tskb5
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    k8s-app: nginx
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}

