kind: Pod
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    k8s-app: rabbitmq
spec:
  containers:
    - name: rabbitmq
      image: 'rabbitmq:3.8.9-management-alpine'
      resources: {}
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status: {}
