kind: Service
apiVersion: v1
metadata:
  name: sfu-monitoring
  labels:
    k8s-app: sfu-monitoring
spec:
  selector:
    k8s-app: sfu
  ports:
  - name: prometheus
    port: 2112
---
kind: Service
apiVersion: v1
metadata:
  name: sfu-monitoring
  namespace: monitoring
spec:
  type: ExternalName
  externalName: sfu-monitoring.default.svc.cluster.local
  ports:
  - port: 2112
    name: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sfu-monitoring
  namespace: monitoring
spec:
  selector:
    matchLabels:
      k8s-app: sfu-monitoring
  endpoints:
  - port: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      k8s-app: sfu-monitoring
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
