{
 "title": "Kafka",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Broker Topics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_controller_channel_metrics_connection_count"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_controller_channel_metrics_request_rate"
    }
   ]
  },
  {
   "title": "Produce Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_produce_queue_size"
    }
   ]
  }
 ]
}