kind: Service
apiVersion: v1
metadata:
  name: grafana
spec:
  ports:
    - name: tcp-3000-3000
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    k8s-app: grafana
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}

