kind: Pod
apiVersion: v1
metadata:
  name: grafana
  labels:
    k8s-app: grafana
  namespace: monitoring
spec:
  containers:
    - name: grafana
      image: 'itcoursevideochat/grafana:latest'
      ports:
        - containerPort: 3000
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  enableServiceLinks: true
status: {}
