kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  labels:
    k8s-app: rabbitmq
spec:
  clusterIP: None
  ports:
   - name: http
     protocol: TCP
     port: 15672
   - name: amqp
     protocol: TCP
     port: 5672
  selector:
    k8s-app: rabbitmq
