apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfu 
spec:
  selector:
    matchLabels:
      k8s-app: sfu 
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: sfu 
    spec:
      containers:
        - name: sfu
          image: 'itcoursevideochat/sfu:latest'
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              cpu: "150m"
              memory: "256Mi"
          imagePullPolicy: IfNotPresent
          env:
            - name: SFU_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      preemptionPolicy: PreemptLowerPriority
