apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfu 
spec:
  selector:
    matchLabels:
      k8s-app: sfu 
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: sfu 
    spec:
      containers:
        - name: sfu
          image: 'itcoursevideochat/sfu:latest'
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
          imagePullPolicy: IfNotPresent
          env:
            - name: SFU_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      preemptionPolicy: PreemptLowerPriority
