kind: Service
apiVersion: v1
metadata:
  name: turn
  labels:
    k8s-app: turn
spec:
  ports:
  - name: udp-3478-3478
    protocol: UDP
    port: 3478
    targetPort: 3478
  selector:
    k8s-app: turn
  type: LoadBalancer 
  sessionAffinity: "ClientIP"
  externalTrafficPolicy: Cluster
