apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/alex/bin/kompose convert -o k8s
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
    - name: "GUI"
      port: 3005
      targetPort: 3000
  selector:
    io.kompose.service: grafana
status:
  loadBalancer: {}
