apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: turn
  name: turn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: turn
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s
        kompose.version: 1.17.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: turn
    spec:
      containers:
        - image: itcoursevideochat/turn:latest
          name: turn
          ports:
            - containerPort: 3478
            - containerPort: 3478
              protocol: UDP
            - containerPort: 50000
              protocol: UDP
            - containerPort: 50001
              protocol: UDP
            - containerPort: 50002
              protocol: UDP
            - containerPort: 50003
              protocol: UDP
            - containerPort: 50004
              protocol: UDP
            - containerPort: 50005
              protocol: UDP
            - containerPort: 50006
              protocol: UDP
            - containerPort: 50007
              protocol: UDP
            - containerPort: 50008
              protocol: UDP
            - containerPort: 50009
              protocol: UDP
            - containerPort: 50010
              protocol: UDP
            - containerPort: 50011
              protocol: UDP
            - containerPort: 50012
              protocol: UDP
            - containerPort: 50013
              protocol: UDP
            - containerPort: 50014
              protocol: UDP
            - containerPort: 50015
              protocol: UDP
            - containerPort: 50016
              protocol: UDP
            - containerPort: 50017
              protocol: UDP
            - containerPort: 50018
              protocol: UDP
            - containerPort: 50019
              protocol: UDP
            - containerPort: 50020
              protocol: UDP
            - containerPort: 50021
              protocol: UDP
            - containerPort: 50022
              protocol: UDP
            - containerPort: 50023
              protocol: UDP
            - containerPort: 50024
              protocol: UDP
            - containerPort: 50025
              protocol: UDP
            - containerPort: 50026
              protocol: UDP
            - containerPort: 50027
              protocol: UDP
            - containerPort: 50028
              protocol: UDP
            - containerPort: 50029
              protocol: UDP
            - containerPort: 50030
              protocol: UDP
            - containerPort: 50031
              protocol: UDP
            - containerPort: 50032
              protocol: UDP
            - containerPort: 50033
              protocol: UDP
            - containerPort: 50034
              protocol: UDP
            - containerPort: 50035
              protocol: UDP
            - containerPort: 50036
              protocol: UDP
            - containerPort: 50037
              protocol: UDP
            - containerPort: 50038
              protocol: UDP
            - containerPort: 50039
              protocol: UDP
            - containerPort: 50040
              protocol: UDP
            - containerPort: 50041
              protocol: UDP
            - containerPort: 50042
              protocol: UDP
            - containerPort: 50043
              protocol: UDP
            - containerPort: 50044
              protocol: UDP
            - containerPort: 50045
              protocol: UDP
            - containerPort: 50046
              protocol: UDP
            - containerPort: 50047
              protocol: UDP
            - containerPort: 50048
              protocol: UDP
            - containerPort: 50049
              protocol: UDP
            - containerPort: 50050
              protocol: UDP
            - containerPort: 50051
              protocol: UDP
            - containerPort: 50052
              protocol: UDP
            - containerPort: 50053
              protocol: UDP
            - containerPort: 50054
              protocol: UDP
            - containerPort: 50055
              protocol: UDP
            - containerPort: 50056
              protocol: UDP
            - containerPort: 50057
              protocol: UDP
            - containerPort: 50058
              protocol: UDP
            - containerPort: 50059
              protocol: UDP
            - containerPort: 50060
              protocol: UDP
            - containerPort: 50061
              protocol: UDP
            - containerPort: 50062
              protocol: UDP
            - containerPort: 50063
              protocol: UDP
            - containerPort: 50064
              protocol: UDP
            - containerPort: 50065
              protocol: UDP
            - containerPort: 50066
              protocol: UDP
            - containerPort: 50067
              protocol: UDP
            - containerPort: 50068
              protocol: UDP
            - containerPort: 50069
              protocol: UDP
            - containerPort: 50070
              protocol: UDP
            - containerPort: 50071
              protocol: UDP
            - containerPort: 50072
              protocol: UDP
            - containerPort: 50073
              protocol: UDP
            - containerPort: 50074
              protocol: UDP
            - containerPort: 50075
              protocol: UDP
            - containerPort: 50076
              protocol: UDP
            - containerPort: 50077
              protocol: UDP
            - containerPort: 50078
              protocol: UDP
            - containerPort: 50079
              protocol: UDP
            - containerPort: 50080
              protocol: UDP
            - containerPort: 50081
              protocol: UDP
            - containerPort: 50082
              protocol: UDP
            - containerPort: 50083
              protocol: UDP
            - containerPort: 50084
              protocol: UDP
            - containerPort: 50085
              protocol: UDP
            - containerPort: 50086
              protocol: UDP
            - containerPort: 50087
              protocol: UDP
            - containerPort: 50088
              protocol: UDP
            - containerPort: 50089
              protocol: UDP
            - containerPort: 50090
              protocol: UDP
            - containerPort: 50091
              protocol: UDP
            - containerPort: 50092
              protocol: UDP
            - containerPort: 50093
              protocol: UDP
            - containerPort: 50094
              protocol: UDP
            - containerPort: 50095
              protocol: UDP
            - containerPort: 50096
              protocol: UDP
            - containerPort: 50097
              protocol: UDP
            - containerPort: 50098
              protocol: UDP
            - containerPort: 50099
              protocol: UDP
            - containerPort: 50100
              protocol: UDP
            - containerPort: 50000
            - containerPort: 50001
            - containerPort: 50002
            - containerPort: 50003
            - containerPort: 50004
            - containerPort: 50005
            - containerPort: 50006
            - containerPort: 50007
            - containerPort: 50008
            - containerPort: 50009
            - containerPort: 50010
            - containerPort: 50011
            - containerPort: 50012
            - containerPort: 50013
            - containerPort: 50014
            - containerPort: 50015
            - containerPort: 50016
            - containerPort: 50017
            - containerPort: 50018
            - containerPort: 50019
            - containerPort: 50020
            - containerPort: 50021
            - containerPort: 50022
            - containerPort: 50023
            - containerPort: 50024
            - containerPort: 50025
            - containerPort: 50026
            - containerPort: 50027
            - containerPort: 50028
            - containerPort: 50029
            - containerPort: 50030
            - containerPort: 50031
            - containerPort: 50032
            - containerPort: 50033
            - containerPort: 50034
            - containerPort: 50035
            - containerPort: 50036
            - containerPort: 50037
            - containerPort: 50038
            - containerPort: 50039
            - containerPort: 50040
            - containerPort: 50041
            - containerPort: 50042
            - containerPort: 50043
            - containerPort: 50044
            - containerPort: 50045
            - containerPort: 50046
            - containerPort: 50047
            - containerPort: 50048
            - containerPort: 50049
            - containerPort: 50050
            - containerPort: 50051
            - containerPort: 50052
            - containerPort: 50053
            - containerPort: 50054
            - containerPort: 50055
            - containerPort: 50056
            - containerPort: 50057
            - containerPort: 50058
            - containerPort: 50059
            - containerPort: 50060
            - containerPort: 50061
            - containerPort: 50062
            - containerPort: 50063
            - containerPort: 50064
            - containerPort: 50065
            - containerPort: 50066
            - containerPort: 50067
            - containerPort: 50068
            - containerPort: 50069
            - containerPort: 50070
            - containerPort: 50071
            - containerPort: 50072
            - containerPort: 50073
            - containerPort: 50074
            - containerPort: 50075
            - containerPort: 50076
            - containerPort: 50077
            - containerPort: 50078
            - containerPort: 50079
            - containerPort: 50080
            - containerPort: 50081
            - containerPort: 50082
            - containerPort: 50083
            - containerPort: 50084
            - containerPort: 50085
            - containerPort: 50086
            - containerPort: 50087
            - containerPort: 50088
            - containerPort: 50089
            - containerPort: 50090
            - containerPort: 50091
            - containerPort: 50092
            - containerPort: 50093
            - containerPort: 50094
            - containerPort: 50095
            - containerPort: 50096
            - containerPort: 50097
            - containerPort: 50098
            - containerPort: 50099
            - containerPort: 50100
          resources: {}
      restartPolicy: Always
status: {}
