apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s
    kompose.version: 1.17.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: turn
  name: turn
spec:
  ports:
    - name: "3478"
      port: 3478
      targetPort: 3478
    - name: 3478-udp
      port: 3478
      protocol: UDP
      targetPort: 3478
    - name: "50000"
      port: 50000
      protocol: UDP
      targetPort: 50000
    - name: "50001"
      port: 50001
      protocol: UDP
      targetPort: 50001
    - name: "50002"
      port: 50002
      protocol: UDP
      targetPort: 50002
    - name: "50003"
      port: 50003
      protocol: UDP
      targetPort: 50003
    - name: "50004"
      port: 50004
      protocol: UDP
      targetPort: 50004
    - name: "50005"
      port: 50005
      protocol: UDP
      targetPort: 50005
    - name: "50006"
      port: 50006
      protocol: UDP
      targetPort: 50006
    - name: "50007"
      port: 50007
      protocol: UDP
      targetPort: 50007
    - name: "50008"
      port: 50008
      protocol: UDP
      targetPort: 50008
    - name: "50009"
      port: 50009
      protocol: UDP
      targetPort: 50009
    - name: "50010"
      port: 50010
      protocol: UDP
      targetPort: 50010
    - name: "50011"
      port: 50011
      protocol: UDP
      targetPort: 50011
    - name: "50012"
      port: 50012
      protocol: UDP
      targetPort: 50012
    - name: "50013"
      port: 50013
      protocol: UDP
      targetPort: 50013
    - name: "50014"
      port: 50014
      protocol: UDP
      targetPort: 50014
    - name: "50015"
      port: 50015
      protocol: UDP
      targetPort: 50015
    - name: "50016"
      port: 50016
      protocol: UDP
      targetPort: 50016
    - name: "50017"
      port: 50017
      protocol: UDP
      targetPort: 50017
    - name: "50018"
      port: 50018
      protocol: UDP
      targetPort: 50018
    - name: "50019"
      port: 50019
      protocol: UDP
      targetPort: 50019
    - name: "50020"
      port: 50020
      protocol: UDP
      targetPort: 50020
    - name: "50021"
      port: 50021
      protocol: UDP
      targetPort: 50021
    - name: "50022"
      port: 50022
      protocol: UDP
      targetPort: 50022
    - name: "50023"
      port: 50023
      protocol: UDP
      targetPort: 50023
    - name: "50024"
      port: 50024
      protocol: UDP
      targetPort: 50024
    - name: "50025"
      port: 50025
      protocol: UDP
      targetPort: 50025
    - name: "50026"
      port: 50026
      protocol: UDP
      targetPort: 50026
    - name: "50027"
      port: 50027
      protocol: UDP
      targetPort: 50027
    - name: "50028"
      port: 50028
      protocol: UDP
      targetPort: 50028
    - name: "50029"
      port: 50029
      protocol: UDP
      targetPort: 50029
    - name: "50030"
      port: 50030
      protocol: UDP
      targetPort: 50030
    - name: "50031"
      port: 50031
      protocol: UDP
      targetPort: 50031
    - name: "50032"
      port: 50032
      protocol: UDP
      targetPort: 50032
    - name: "50033"
      port: 50033
      protocol: UDP
      targetPort: 50033
    - name: "50034"
      port: 50034
      protocol: UDP
      targetPort: 50034
    - name: "50035"
      port: 50035
      protocol: UDP
      targetPort: 50035
    - name: "50036"
      port: 50036
      protocol: UDP
      targetPort: 50036
    - name: "50037"
      port: 50037
      protocol: UDP
      targetPort: 50037
    - name: "50038"
      port: 50038
      protocol: UDP
      targetPort: 50038
    - name: "50039"
      port: 50039
      protocol: UDP
      targetPort: 50039
    - name: "50040"
      port: 50040
      protocol: UDP
      targetPort: 50040
    - name: "50041"
      port: 50041
      protocol: UDP
      targetPort: 50041
    - name: "50042"
      port: 50042
      protocol: UDP
      targetPort: 50042
    - name: "50043"
      port: 50043
      protocol: UDP
      targetPort: 50043
    - name: "50044"
      port: 50044
      protocol: UDP
      targetPort: 50044
    - name: "50045"
      port: 50045
      protocol: UDP
      targetPort: 50045
    - name: "50046"
      port: 50046
      protocol: UDP
      targetPort: 50046
    - name: "50047"
      port: 50047
      protocol: UDP
      targetPort: 50047
    - name: "50048"
      port: 50048
      protocol: UDP
      targetPort: 50048
    - name: "50049"
      port: 50049
      protocol: UDP
      targetPort: 50049
    - name: "50050"
      port: 50050
      protocol: UDP
      targetPort: 50050
    - name: "50051"
      port: 50051
      protocol: UDP
      targetPort: 50051
    - name: "50052"
      port: 50052
      protocol: UDP
      targetPort: 50052
    - name: "50053"
      port: 50053
      protocol: UDP
      targetPort: 50053
    - name: "50054"
      port: 50054
      protocol: UDP
      targetPort: 50054
    - name: "50055"
      port: 50055
      protocol: UDP
      targetPort: 50055
    - name: "50056"
      port: 50056
      protocol: UDP
      targetPort: 50056
    - name: "50057"
      port: 50057
      protocol: UDP
      targetPort: 50057
    - name: "50058"
      port: 50058
      protocol: UDP
      targetPort: 50058
    - name: "50059"
      port: 50059
      protocol: UDP
      targetPort: 50059
    - name: "50060"
      port: 50060
      protocol: UDP
      targetPort: 50060
    - name: "50061"
      port: 50061
      protocol: UDP
      targetPort: 50061
    - name: "50062"
      port: 50062
      protocol: UDP
      targetPort: 50062
    - name: "50063"
      port: 50063
      protocol: UDP
      targetPort: 50063
    - name: "50064"
      port: 50064
      protocol: UDP
      targetPort: 50064
    - name: "50065"
      port: 50065
      protocol: UDP
      targetPort: 50065
    - name: "50066"
      port: 50066
      protocol: UDP
      targetPort: 50066
    - name: "50067"
      port: 50067
      protocol: UDP
      targetPort: 50067
    - name: "50068"
      port: 50068
      protocol: UDP
      targetPort: 50068
    - name: "50069"
      port: 50069
      protocol: UDP
      targetPort: 50069
    - name: "50070"
      port: 50070
      protocol: UDP
      targetPort: 50070
    - name: "50071"
      port: 50071
      protocol: UDP
      targetPort: 50071
    - name: "50072"
      port: 50072
      protocol: UDP
      targetPort: 50072
    - name: "50073"
      port: 50073
      protocol: UDP
      targetPort: 50073
    - name: "50074"
      port: 50074
      protocol: UDP
      targetPort: 50074
    - name: "50075"
      port: 50075
      protocol: UDP
      targetPort: 50075
    - name: "50076"
      port: 50076
      protocol: UDP
      targetPort: 50076
    - name: "50077"
      port: 50077
      protocol: UDP
      targetPort: 50077
    - name: "50078"
      port: 50078
      protocol: UDP
      targetPort: 50078
    - name: "50079"
      port: 50079
      protocol: UDP
      targetPort: 50079
    - name: "50080"
      port: 50080
      protocol: UDP
      targetPort: 50080
    - name: "50081"
      port: 50081
      protocol: UDP
      targetPort: 50081
    - name: "50082"
      port: 50082
      protocol: UDP
      targetPort: 50082
    - name: "50083"
      port: 50083
      protocol: UDP
      targetPort: 50083
    - name: "50084"
      port: 50084
      protocol: UDP
      targetPort: 50084
    - name: "50085"
      port: 50085
      protocol: UDP
      targetPort: 50085
    - name: "50086"
      port: 50086
      protocol: UDP
      targetPort: 50086
    - name: "50087"
      port: 50087
      protocol: UDP
      targetPort: 50087
    - name: "50088"
      port: 50088
      protocol: UDP
      targetPort: 50088
    - name: "50089"
      port: 50089
      protocol: UDP
      targetPort: 50089
    - name: "50090"
      port: 50090
      protocol: UDP
      targetPort: 50090
    - name: "50091"
      port: 50091
      protocol: UDP
      targetPort: 50091
    - name: "50092"
      port: 50092
      protocol: UDP
      targetPort: 50092
    - name: "50093"
      port: 50093
      protocol: UDP
      targetPort: 50093
    - name: "50094"
      port: 50094
      protocol: UDP
      targetPort: 50094
    - name: "50095"
      port: 50095
      protocol: UDP
      targetPort: 50095
    - name: "50096"
      port: 50096
      protocol: UDP
      targetPort: 50096
    - name: "50097"
      port: 50097
      protocol: UDP
      targetPort: 50097
    - name: "50098"
      port: 50098
      protocol: UDP
      targetPort: 50098
    - name: "50099"
      port: 50099
      protocol: UDP
      targetPort: 50099
    - name: "50100"
      port: 50100
      protocol: UDP
      targetPort: 50100
    - name: 50000-tcp
      port: 50000
      targetPort: 50000
    - name: 50001-tcp
      port: 50001
      targetPort: 50001
    - name: 50002-tcp
      port: 50002
      targetPort: 50002
    - name: 50003-tcp
      port: 50003
      targetPort: 50003
    - name: 50004-tcp
      port: 50004
      targetPort: 50004
    - name: 50005-tcp
      port: 50005
      targetPort: 50005
    - name: 50006-tcp
      port: 50006
      targetPort: 50006
    - name: 50007-tcp
      port: 50007
      targetPort: 50007
    - name: 50008-tcp
      port: 50008
      targetPort: 50008
    - name: 50009-tcp
      port: 50009
      targetPort: 50009
    - name: 50010-tcp
      port: 50010
      targetPort: 50010
    - name: 50011-tcp
      port: 50011
      targetPort: 50011
    - name: 50012-tcp
      port: 50012
      targetPort: 50012
    - name: 50013-tcp
      port: 50013
      targetPort: 50013
    - name: 50014-tcp
      port: 50014
      targetPort: 50014
    - name: 50015-tcp
      port: 50015
      targetPort: 50015
    - name: 50016-tcp
      port: 50016
      targetPort: 50016
    - name: 50017-tcp
      port: 50017
      targetPort: 50017
    - name: 50018-tcp
      port: 50018
      targetPort: 50018
    - name: 50019-tcp
      port: 50019
      targetPort: 50019
    - name: 50020-tcp
      port: 50020
      targetPort: 50020
    - name: 50021-tcp
      port: 50021
      targetPort: 50021
    - name: 50022-tcp
      port: 50022
      targetPort: 50022
    - name: 50023-tcp
      port: 50023
      targetPort: 50023
    - name: 50024-tcp
      port: 50024
      targetPort: 50024
    - name: 50025-tcp
      port: 50025
      targetPort: 50025
    - name: 50026-tcp
      port: 50026
      targetPort: 50026
    - name: 50027-tcp
      port: 50027
      targetPort: 50027
    - name: 50028-tcp
      port: 50028
      targetPort: 50028
    - name: 50029-tcp
      port: 50029
      targetPort: 50029
    - name: 50030-tcp
      port: 50030
      targetPort: 50030
    - name: 50031-tcp
      port: 50031
      targetPort: 50031
    - name: 50032-tcp
      port: 50032
      targetPort: 50032
    - name: 50033-tcp
      port: 50033
      targetPort: 50033
    - name: 50034-tcp
      port: 50034
      targetPort: 50034
    - name: 50035-tcp
      port: 50035
      targetPort: 50035
    - name: 50036-tcp
      port: 50036
      targetPort: 50036
    - name: 50037-tcp
      port: 50037
      targetPort: 50037
    - name: 50038-tcp
      port: 50038
      targetPort: 50038
    - name: 50039-tcp
      port: 50039
      targetPort: 50039
    - name: 50040-tcp
      port: 50040
      targetPort: 50040
    - name: 50041-tcp
      port: 50041
      targetPort: 50041
    - name: 50042-tcp
      port: 50042
      targetPort: 50042
    - name: 50043-tcp
      port: 50043
      targetPort: 50043
    - name: 50044-tcp
      port: 50044
      targetPort: 50044
    - name: 50045-tcp
      port: 50045
      targetPort: 50045
    - name: 50046-tcp
      port: 50046
      targetPort: 50046
    - name: 50047-tcp
      port: 50047
      targetPort: 50047
    - name: 50048-tcp
      port: 50048
      targetPort: 50048
    - name: 50049-tcp
      port: 50049
      targetPort: 50049
    - name: 50050-tcp
      port: 50050
      targetPort: 50050
    - name: 50051-tcp
      port: 50051
      targetPort: 50051
    - name: 50052-tcp
      port: 50052
      targetPort: 50052
    - name: 50053-tcp
      port: 50053
      targetPort: 50053
    - name: 50054-tcp
      port: 50054
      targetPort: 50054
    - name: 50055-tcp
      port: 50055
      targetPort: 50055
    - name: 50056-tcp
      port: 50056
      targetPort: 50056
    - name: 50057-tcp
      port: 50057
      targetPort: 50057
    - name: 50058-tcp
      port: 50058
      targetPort: 50058
    - name: 50059-tcp
      port: 50059
      targetPort: 50059
    - name: 50060-tcp
      port: 50060
      targetPort: 50060
    - name: 50061-tcp
      port: 50061
      targetPort: 50061
    - name: 50062-tcp
      port: 50062
      targetPort: 50062
    - name: 50063-tcp
      port: 50063
      targetPort: 50063
    - name: 50064-tcp
      port: 50064
      targetPort: 50064
    - name: 50065-tcp
      port: 50065
      targetPort: 50065
    - name: 50066-tcp
      port: 50066
      targetPort: 50066
    - name: 50067-tcp
      port: 50067
      targetPort: 50067
    - name: 50068-tcp
      port: 50068
      targetPort: 50068
    - name: 50069-tcp
      port: 50069
      targetPort: 50069
    - name: 50070-tcp
      port: 50070
      targetPort: 50070
    - name: 50071-tcp
      port: 50071
      targetPort: 50071
    - name: 50072-tcp
      port: 50072
      targetPort: 50072
    - name: 50073-tcp
      port: 50073
      targetPort: 50073
    - name: 50074-tcp
      port: 50074
      targetPort: 50074
    - name: 50075-tcp
      port: 50075
      targetPort: 50075
    - name: 50076-tcp
      port: 50076
      targetPort: 50076
    - name: 50077-tcp
      port: 50077
      targetPort: 50077
    - name: 50078-tcp
      port: 50078
      targetPort: 50078
    - name: 50079-tcp
      port: 50079
      targetPort: 50079
    - name: 50080-tcp
      port: 50080
      targetPort: 50080
    - name: 50081-tcp
      port: 50081
      targetPort: 50081
    - name: 50082-tcp
      port: 50082
      targetPort: 50082
    - name: 50083-tcp
      port: 50083
      targetPort: 50083
    - name: 50084-tcp
      port: 50084
      targetPort: 50084
    - name: 50085-tcp
      port: 50085
      targetPort: 50085
    - name: 50086-tcp
      port: 50086
      targetPort: 50086
    - name: 50087-tcp
      port: 50087
      targetPort: 50087
    - name: 50088-tcp
      port: 50088
      targetPort: 50088
    - name: 50089-tcp
      port: 50089
      targetPort: 50089
    - name: 50090-tcp
      port: 50090
      targetPort: 50090
    - name: 50091-tcp
      port: 50091
      targetPort: 50091
    - name: 50092-tcp
      port: 50092
      targetPort: 50092
    - name: 50093-tcp
      port: 50093
      targetPort: 50093
    - name: 50094-tcp
      port: 50094
      targetPort: 50094
    - name: 50095-tcp
      port: 50095
      targetPort: 50095
    - name: 50096-tcp
      port: 50096
      targetPort: 50096
    - name: 50097-tcp
      port: 50097
      targetPort: 50097
    - name: 50098-tcp
      port: 50098
      targetPort: 50098
    - name: 50099-tcp
      port: 50099
      targetPort: 50099
    - name: 50100-tcp
      port: 50100
      targetPort: 50100
  selector:
    io.kompose.service: turn
status:
  loadBalancer: {}
