apiVersion: tarantool.io/v1alpha1
kind: Cluster
metadata:
  name: tarantool-cluster
spec:
  selector:
    matchLabels:
      tarantool.io/cluster-id: "tarantool-cluster"
---
apiVersion: tarantool.io/v1alpha1
kind: Role
metadata:
  name: storage
  labels:
    tarantool.io/cluster-id: "tarantool-cluster"
    tarantool.io/role: "storage"
spec:
  selector:
    matchLabels:
      tarantool.io/replicaset-template: "storage-template"
  numReplicasets: 1
---
apiVersion: tarantool.io/v1alpha1
kind: Role
metadata:
  name: routers
  labels:
    tarantool.io/cluster-id: "tarantool-cluster"
    tarantool.io/role: "router"
spec:
  selector:
    matchLabels:
      tarantool.io/replicaset-template: "router-template"
  numReplicasets: 1
---
apiVersion: tarantool.io/v1alpha1
kind: ReplicasetTemplate
metadata:
  name: storage-template
  labels:
    tarantool.io/cluster-id: "tarantool-cluster"
    tarantool.io/replicaset-template: "storage-template"
    tarantool.io/role: "storage"
spec:
  replicas: 1
  selector:
    matchLabels:
      tarantool.io/pod-template: "storage-pod-template"
  template:
    metadata:
      labels:
        tarantool.io/cluster-id: "tarantool-cluster"
        tarantool.io/pod-template: "storage-pod-template"
    spec:
      terminationGracePeriodSeconds: 10
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: pim-storage
        image: itcoursevideochat/tarantool
        ports:
          - containerPort: 3301
        env:
          - name: TARANTOOL_INSTANCE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: TARANTOOL_MEMTX_MEMORY
            value: "33554432"
          - name: TARANTOOL_LOG
            value: "/dev/stdout"
          - name: TARANTOOL_ADVERTISE_HOST
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: TARANTOOL_ADVERTISE_URI
            value: "$(TARANTOOL_ADVERTISE_HOST).tarantool-cluster:3301"
          - name: TARANTOOL_USER_NAME
            value: tarantool
          - name: TARANTOOL_USER_PASSWORD
            value: tarantoolpwd
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
---
apiVersion: tarantool.io/v1alpha1
kind: ReplicasetTemplate
metadata:
  name: router-template
  labels:
    tarantool.io/cluster-id: "tarantool-cluster"
    tarantool.io/replicaset-template: "router-template"
    tarantool.io/role: "router"
spec:
  replicas: 1
  selector:
    matchLabels:
      tarantool.io/pod-template: "router-pod-template"
  template:
    metadata:
      labels:
        tarantool.io/cluster-id: "tarantool-cluster"
        tarantool.io/pod-template: "router-pod-template"
    spec:
      terminationGracePeriodSeconds: 10
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: pim-router
        image: itcoursevideochat/tarantool
        ports:
          - containerPort: 3301
        env:
          - name: TARANTOOL_INSTANCE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: TARANTOOL_MEMTX_MEMORY
            value: "33554432"
          - name: TARANTOOL_LOG
            value: "/dev/stdout"
          - name: TARANTOOL_ADVERTISE_HOST
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: TARANTOOL_ADVERTISE_URI
            value: "$(TARANTOOL_ADVERTISE_HOST).tarantool-cluster:3301"
          - name: TARANTOOL_USER_NAME
            value: tarantool
          - name: TARANTOOL_USER_PASSWORD
            value: tarantoolpwd
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: tarantool-cluster 
  labels:
    tarantool.io/role: "router"
spec:
  ports:
    - port: 3301
      name: web
      protocol: TCP
  selector:
    tarantool.io/role: "router"
